### ISSUE TITLE
Dataset and Checkpoints Links down

### ISSUE THREAD

**Issue by iamamiramine** [ChristophReich1996/Multi-StyleGAN#1]
I am trying to download the dataset and the checkpoints from the provided links, however, accessing the links gives me a server error.
Any way I could access them?
Thank you.

**Comment by ChristophReich1996** [comment]
Hi @iamamiramine, thanks for your interest in our work. Both the dataset and the checkpoints are hosted by the university. They seem to have storage issues, currently. I hope this problem should be fixed by the university in the upcoming days. I will keep you updated on this.

![Screenshot 2024-02-26 at 17 39 59](https://github.com/ChristophReich1996/Multi-StyleGAN/assets/34400551/21684a04-0d9b-48bd-9d6b-358b8573db72)

**Comment by iamamiramine** [comment]
Okay no worries. Thank you for you reply!

**Comment by ChristophReich1996** [comment]
Hi @iamamiramine, downloads should work now.
